name: EKS via Terraform

on:
  workflow_dispatch:
  pull_request:
    branches:
      - feature*
      - development
      - stage
      - production

jobs:
  eks:
    uses: LinconFreitas/templates/.github/workflows/terraform-execution.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
